name: Publish a PR Artifact
description: Publishes an Artifact that a PR build created

runs:
  using: "composite"
  steps:
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pr_${{ github.event.number }}_release
        path: ${{ github.workspace }}/_build/
        retention-days: 5
