name: "Continous Integration: Releases"

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    
    #SemVer calculation
    - name: Get Next Version
      id: semver
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ github.token }}
        branch: main

    - uses: ./.github/actions/build/
    - uses: ./.github/actions/publish-artifact-release/