name: "Continous Integration: PRs"

on:
  pull_request:
    types:
    - opened
    - reopened
    - review_requested
    - synchronize
    # - edited #updating PR title, body, state or base?

jobs:
  check-pr:
    name: Validate Release Label and Notes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jefflinse/pr-semver-bump@v1.6.0
        name: Validate Pull Request Metadata
        with:
          mode: validate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          require-release-notes: true
          release-notes-prefix: -- begin release notes --
          release-notes-suffix: -- end release notes --
          noop-labels:
            - documentation change
          major-label: SemVer Major
          minor-label: SemVer Minor
          patch-label: SemVer Patch

  build:
    name: Build Solution
    runs-on: windows-2019
    needs: check-pr

    steps:
    - uses: actions/checkout@v4
      name: Checkout Source
      with:
        fetch-tags: true

    - uses: ./.github/actions/build/
      name: Build Source

    - uses: ./.github/actions/publish-artifact-pr/
      name: Publish Artifact
