name: Continous Integration

on:
  pull_request:
    types: 
    - opened
    - reopened
    - review_requested
    - synchronize
    # - edited #updating PR title, body, state or base?

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: ./.github/workflows/build.yaml
    
